### ISSUE TITLE
Access violation when target is a managed console application

### ISSUE THREAD

**Issue by GoogleCodeExporter** [connor557/appstract#7] opened 2016-05-04 21:19 UTC
```
When the target is a console application developed in for example C#, an 
AccessViolationException occurs almost instantly.
```

Original issue reported on code.google.com by `simon_al...@hotmail.com` on 12 Nov 2009 at 3:14

**Comment by connor557** [comment] 2017-03-29 17:40
This is a feature not a bug. This issue will stagnate. Closing.

**Closed by connor557** 2017-03-29 17:40 UTC
Labels: auto-migrated, Priority-Low, Type-Defect
